{
 "title": "Status overview",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Ordered drinks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(nine_barsim_drink_order_total) by (drinkname)",
     "legendFormat": "Ordered {{drinkname}}"
    },
    {
     "expr": "sum(nine_barsim_drink_order_total) by (drinkname)",
     "legendFormat": "{{drinkname}}"
    }
   ]
  },
  {
   "title": "Active bartenders",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 0 },
   "targets": [
    { "expr": "nine_barsim_bartender_active" }
   ]
  },
  {
   "title": "Drinks in queue",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 5, "x": 19, "y": 3 },
   "targets": [
    { "expr": "nine_barsim_drinksqueue_size" }
   ]
  },
  {
   "title": "Served drinks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(nine_barsim_drink_served_total) by (drinkname)",
     "legendFormat": "{{drinkname}}"
    }
   ]
  },
  {
   "title": "Queued drinks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(nine_barsim_drink_order_total) by (drinkname) - sum(nine_barsim_drink_served_total) by (drinkname)",
     "legendFormat": "{{drinkname}}"
    }
   ]
  },
  {
   "title": "Bartenders work",
   "type": "graph",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(nine_barsim_drink_served_total) by (bartender)",
     "legendFormat": "{{bartender}}"
    }
   ]
  },
  {
   "title": "Top 10 Nine Colada Niners",
   "type": "graph",
   "gridPos": { "h": 6, "w": 19, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10, nine_barsim_drink_order_total{drinkname=\"Nine Colada\"})",
     "legendFormat": "{{niner}}"
    }
   ]
  },
  {
   "title": "Prometheus status",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 34 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{job=\"prometheus\"}"
    }
   ]
  },
  {
   "title": "Up",
   "type": "graph",
   "gridPos": { "h": 10, "w": 20, "x": 4, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "up", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Barsim status",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 39 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{job=\"barsim\"}"
    }
   ]
  }
 ]
}